import i18n from "@/lib/i18n";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={await i18n.getLocale()}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="/en">English</Link>
              </li>
              <li>
                <Link href="/sv">Svenska</Link>
              </li>
              <li>
                <Link href="/es">Español</Link>
              </li>
              <li>
                <Link href="/fr">Français</Link>
              </li>
            </ul>
          </nav>
          <hr />
        </header>
        {children}
      </body>
    </html>
  );
}
